/**
 * Row objects to SQL text. Pure, so the emitted artefact is golden-testable.
 *
 * The loader emits SQL rather than writing to a database directly. That is a
 * deliberate choice and it buys two things:
 *
 *   A human can read a diff before anything reaches a database. "No agent
 *   publishes content" is easy to assert and hard to guarantee; a reviewable
 *   artefact between the agent and the data is the guarantee.
 *
 *   The same artefact applies to local Postgres today and to Supabase later,
 *   with no code path that exists only in one of them.
 */

/** A SQL literal for a value. Strings are escaped by doubling the quote. */
export function literal(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) {
      throw new Error(`Refusing to emit a non-finite number: ${value}`);
    }
    return String(value);
  }
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (value instanceof Date) return `'${value.toISOString()}'`;
  if (typeof value === 'object') {
    return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

/**
 * An INSERT ... ON CONFLICT DO UPDATE over a set of rows.
 *
 * Every row must have the same keys, in the same order, so the emitted
 * statement is one multi-row insert rather than a hundred single-row ones.
 */
export function upsert(
  table: string,
  rows: Record<string, unknown>[],
  conflictTarget: string,
  options: {
    updateColumns?: string[];
    cast?: Record<string, string>;
    /**
     * Re-inserting an identical row is a no-op rather than an update. Correct
     * where every column forms the conflict key — a citation, for instance, is
     * fully described by the record, source and claim it joins, so there is
     * nothing left to change.
     */
    doNothing?: boolean;
  } = {},
): string {
  if (rows.length === 0) return `-- no rows for ${table}\n`;

  const columns = Object.keys(rows[0] as Record<string, unknown>);
  const cast = options.cast ?? {};

  for (const [index, row] of rows.entries()) {
    const keys = Object.keys(row);
    if (keys.length !== columns.length || keys.some((k, i) => k !== columns[i])) {
      throw new Error(
        `Row ${index} of ${table} has different columns to row 0. ` +
          'Every row in an upsert must have the same shape.',
      );
    }
  }

  // Never assign to a column that forms the conflict key: it is what matched.
  const keyColumns = new Set(
    (conflictTarget.match(/[a-z_]+/g) ?? []).filter((word) => columns.includes(word)),
  );

  const values = rows
    .map(
      (row) =>
        '  (' +
        columns
          .map((c) => {
            const lit = literal(row[c]);
            return cast[c] && lit !== 'null' ? `${lit}::${cast[c]}` : lit;
          })
          .join(', ') +
        ')',
    )
    .join(',\n');

  const insert = `insert into ${table} (${columns.join(', ')})\nvalues\n${values}\n`;

  if (options.doNothing) {
    return `${insert}on conflict ${conflictTarget} do nothing;\n`;
  }

  const updates = (options.updateColumns ?? columns.filter((c) => c !== 'id'))
    .filter((c) => !keyColumns.has(c))
    .map((c) => `  ${c} = excluded.${c}`)
    .join(',\n');

  if (updates === '') {
    throw new Error(
      `Every column of ${table} is part of its conflict key, so the upsert ` +
        'would have nothing to update. Pass updateColumns explicitly.',
    );
  }

  return `${insert}on conflict ${conflictTarget} do update set\n${updates};\n`;
}

/**
 * A plain multi-row INSERT, for a table with nothing to conflict with: the
 * temporary staging tables the load reconciles against.
 */
export function insertRows(
  table: string,
  rows: Record<string, unknown>[],
  options: { cast?: Record<string, string> } = {},
): string {
  if (rows.length === 0) return `-- no rows for ${table}\n`;
  const columns = Object.keys(rows[0] as Record<string, unknown>);
  const cast = options.cast ?? {};
  const values = rows
    .map(
      (row) =>
        '  (' +
        columns
          .map((c) => {
            const lit = literal(row[c]);
            return cast[c] && lit !== 'null' ? `${lit}::${cast[c]}` : lit;
          })
          .join(', ') +
        ')',
    )
    .join(',\n');
  return `insert into ${table} (${columns.join(', ')})\nvalues\n${values};\n`;
}

/** A header stating what produced this artefact and from what. */
export function header(meta: {
  loaderVersion: string;
  sourceSystem: string;
  sourceDigest: string;
  counts: Record<string, number>;
}): string {
  const counts = Object.entries(meta.counts)
    .map(([k, v]) => `--   ${k.padEnd(20)} ${v}`)
    .join('\n');

  return (
    `-- Generated by ${meta.loaderVersion}. Do not edit by hand.\n` +
    `--\n` +
    `-- Source system: ${meta.sourceSystem}\n` +
    `-- Source digest: sha256:${meta.sourceDigest}\n` +
    `--\n` +
    `-- Rows:\n${counts}\n` +
    `--\n` +
    `-- This file is derived. It is regenerated by scripts/ingestion/load-pipeline.ts\n` +
    `-- and is deliberately not committed: a second copy of the research in the\n` +
    `-- repository would be a second source of truth.\n\n`
  );
}
