#!/usr/bin/env python3
"""
RG-060 / RG-061: bulk-download and test the signed consents for every determined NSW data centre
SSD, then emit a condition comparison matrix.

Pipeline:
  1. read the archived node JSON index (data/raw/nsw_planning/nodes/)
  2. for each project, rank its attachments and pick the best consent candidate
     (signed instrument of consent > instrument consent > development consent > determination)
  3. resolve field_content_url, skip anything marked field_is_public == false, download with a
     size cap, archive with a SHA-256 manifest
  4. extract text, and ABANDON any document whose yield falls below the reliability floor -
     a low-yield extraction cannot support a negative finding
  5. run the fixed condition battery, the Schedule 1 applicant parse, and the cover-page
     execution block parse (determination date, signatory, delegation, file reference)
  6. write exports/nsw_planning/nsw_dc_consent_conditions.csv and a loadable curated pack

--offline re-analyses the ARCHIVED PDFs/texts without any network access and without
re-extracting: it reads the cached .txt produced by scripts/reextract_consents.py (pypdf).
Prefer it for reproducing the battery. Online mode re-downloads and re-extracts with the
dependency-free pdf_text extractor - note that pdf_text cannot decrypt AES-encrypted
portal PDFs (2 of 20 in the 2026-09-18 archive) and lost text on several others; the
pypdf re-extraction of 2026-09-18 is the better extraction and --offline will not clobber it.

Usage:
    python3 scripts/consent_condition_audit.py --list          # show what would be fetched
    python3 scripts/consent_condition_audit.py --limit 12      # fetch and analyse
    python3 scripts/consent_condition_audit.py --limit 12 --pack
    python3 scripts/consent_condition_audit.py --offline --pack  # re-analyse the archive
"""
from __future__ import annotations

import argparse
import csv
import glob
import hashlib
import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import warnings
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

from pdf_text import extract, yield_stats, LowYieldWarning  # noqa: E402
from reextract_consents import parse_execution, signatory  # noqa: E402

NODES = os.path.join(ROOT, "data", "raw", "nsw_planning", "nodes")
ATT = os.path.join(ROOT, "data", "raw", "nsw_planning", "consents")
OUT_CSV = os.path.join(ROOT, "exports", "nsw_planning", "nsw_dc_consent_conditions.csv")
# Legacy raw-pack emission. NOT wired into the pipelines: the curated, load-bearing pack is
# data/packs/rg060_consent_matrix.json, generated by scripts/curate_rg060.py from the CSV.
# Emitted under retired/ so scripts/check_packs.py never sees an unwired pack in data/packs/.
OUT_PACK = os.path.join(ROOT, "data", "packs", "retired", "rg060_consent_conditions.json")
BASE = "https://www.planningportal.nsw.gov.au"
UA = ("ADCO-research/1.0 (Australian Data Centre Observatory; open public-interest research "
      "database; single-threaded polite crawler; stop on request)")
DELAY = 1.5
MAX_BYTES = 12 * 1024 * 1024
SRC = "SRC_NSWPORTAL_CONSENTS"

# The chars/KB reliability floor misfires on (a) very short instruments and (b) plan-heavy
# PDFs whose bytes are mostly embedded drawings. These two were manually reviewed on
# 2026-09-18 against the pypdf re-extraction: both are complete (cover execution block
# parses; text runs to the document's natural end - the incident-report schedule / drawing
# list) so their negative findings ARE safe. Recorded here rather than silently tweaked.
MANUAL_RELIABLE = {
    "davis_rd_data_centre_mod_1_tree_removal_correction":
        "2-page s4.55 modification; complete (ends at drawing list). Ratio floor misfires "
        "on short documents.",
    "dicker_data_warehouse_and_distribution_centre":
        "2.4 MB plan-heavy PDF; 67k chars extracted, complete (ends at the incident-report "
        "schedule like every other instrument). Ratio floor misfires on embedded drawings.",
}


def node_meta(slug: str) -> dict:
    """Portal determination metadata from the archived node JSON (primary, offline)."""
    path = os.path.join(NODES, f"{slug}.json")
    if not os.path.exists(path):
        return {}
    j = json.load(open(path, encoding="utf-8"))
    g = lambda k: (j.get(k) or [{}])[0].get("value")  # noqa: E731
    return {"determination_date_portal": str(g("field_date_of_determination_mp") or "")[:10],
            "determination_authority_portal": str(g("field_determination_authority") or ""),
            "decision_portal": str(g("field_decision") or "")}


# Rank: lower is better. Only these slug shapes are treated as the consent itself.
CONSENT_RANK = [
    (r"signed.{0,20}(ssd.{0,4})?instrument.{0,4}consent", 0),
    (r"signed.{0,20}determination.{0,10}instrument", 1),
    (r"ssd-\d+-instrument-consent", 2),
    (r"instrument-consent", 3),
    (r"development-consent", 4),
    (r"signed-ssd-determination-instrument", 5),
    (r"determination-instrument", 6),
]
EXCLUDE = re.compile(r"draft|recommendation|assessment-report|notice|mod-\d|modification|"
                     r"owners-consent|landowner|cover-letter|sears", re.I)

# The condition battery. Every pattern is applied to the flattened consent text.
BATTERY = {
    "renewable_ppa_additionality": r"additional,?\s*firmed renewable|power purchase agreement|\bPPA\b|"
                                   r"renewable energy (supply|procurement|generation)",
    "all_times_matching": r"at all times",
    "pue": r"\bPUE\b|power usage effectiveness",
    "wue": r"\bWUE\b|water usage effectiveness",
    "recycled_or_nonpotable_water": r"recycled water|non.?potable",
    "generator_hours_cap": r"does not exceed\s*(\d{2,4})\s*hours per year|"
                           r"(\d{2,4})\s*hours per year",
    # PDF extraction splits "NOx" as "NO x" and inserts spaces around punctuation, so the
    # pattern must tolerate whitespace inside the token. Verified against Glendenning B14(b).
    "nox_mass_cap": r"N\s?O\s?x?.{0,120}?tonnes\s+per\s+year|tonnes\s+per\s+year.{0,90}?N\s?O\s?x",
    "nox_concentration_limit": r"\d{3}\s*m\s?g\s?/\s?m|mg/m3|mg/m³",
    "stack_height": r"stacks?.{0,50}metres|vertical stack",
    "annual_emissions_testing": r"annual emissions test|emissions? test.{0,40}annual",
    "diesel_storage_cap": r"diesel (?:fuel )?storage.{0,90}?(\d[\d,]{0,7})\s*(tonnes|kilolitre|kL|litre)",
    "installed_genset_cap": r"installed generating capacity of\s*(?:more than\s*)?([\d\.,]+)\s*(?:megawatts?|MW)\b",
    "total_power_cap": r"(?:total )?power consumption.{0,40}?does not exceed\s*([\d\.,]+)\s*|"
                       r"power consumption of\s*([\d\.,]+)\s*(?:megawatts?|MW)\b",
    "demand_response": r"demand (?:response|flexibility)|peak (?:demand|load) (?:reduction|management)|curtail",
    "battery_storage": r"battery energy storage|\bBESS\b|battery storage",
    "website_disclosure": r"publicly available|publish.{0,50}website",
    "noise_limits": r"dB\(A\)|LAeq|noise limit",
    "tier_standard": r"Tier\s?[24]|best available techn",
    "clean_air_regulation": r"Clean Air.{0,30}Regulation|Group\s?6",
    "net_zero_or_offsets": r"net zero|carbon neutral|offset",
    "guidelines_cited": r"Data Centre Guidelines",
}


def get(url: str, timeout: int = 240) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return resp.read()


def pick_consent(slug: str) -> tuple[str, int] | None:
    path = os.path.join(NODES, f"{slug}.json")
    if not os.path.exists(path):
        return None
    node = json.load(open(path, encoding="utf-8"))
    atts = [(a.get("url") or "").strip("/") for a in (node.get("field_attachment") or [])]
    best = None
    for a in atts:
        if EXCLUDE.search(a):
            continue
        for pat, rank in CONSENT_RANK:
            if re.search(pat, a, re.I):
                if best is None or rank < best[1]:
                    best = (a, rank)
                break
    return best


def resolve(a_slug: str) -> dict:
    j = json.loads(get(f"{BASE}/{a_slug}?_format=json"))
    cu = (j.get("field_content_url") or [{}])[0]
    return {
        "uri": cu.get("uri"),
        "title": cu.get("title"),
        "is_public": (j.get("field_is_public") or [{}])[0].get("value"),
        "folder": (j.get("field_folder_name") or [{}])[0].get("value"),
        "label": (j.get("field_label") or [{}])[0].get("value"),
    }


def first(rx: str, text: str) -> str:
    m = re.search(rx, text, re.I)
    if not m:
        return ""
    if m.groups():
        for g in m.groups():
            if g:
                return g.strip()
    return "yes"


def analyse(slug: str, txt: str, meta: dict) -> dict:
    flat = re.sub(r"\s+", " ", txt)
    # Glyph-split digit repair: pypdf sometimes emits a space inside numbers positioned as
    # separate glyphs (nextdc s4: "2 94 megawatts" = 294 MW; dicker: "1 088703" = DP 1088703).
    # Collapsing digit-space-digit is safe: no real condition text separates two numbers with
    # only whitespace where merging would change meaning (units/words always intervene).
    flat = re.sub(r"(?<=\d) (?=\d)", "", flat)
    row = {"project": slug, "case_id": "", "title": meta.get("title") or "",
           "determination_date": "", "date_source": "", "determination_date_portal": "",
           "determination_authority_portal": "", "file_ref": "", "delegation_of": "",
           "delegation_executed": "", "signatory_name": "", "signatory_title": "",
           "applicant": "", "consent_authority": "",
           "chars": len(txt), "chars_per_kb": meta.get("chars_per_kb", 0),
           "reliable": meta.get("reliable", False)}
    # portal determination metadata (primary, archived node JSON)
    nm = node_meta(slug)
    row.update(nm)
    # cover-page execution block (instrument's own text)
    ex = parse_execution(txt)
    sg = signatory(txt)
    row["file_ref"] = ex.get("file_ref") or ""
    row["delegation_of"] = ex.get("delegation_of") or ""
    row["delegation_executed"] = ex.get("delegation_executed") or ""
    row["signatory_name"] = sg.get("name") or ""
    row["signatory_title"] = sg.get("title") or ""
    if ex.get("execution_date"):
        row["determination_date"] = ex["execution_date"]
        row["date_source"] = "instrument:" + ex.get("execution_date_source", "")
    elif nm.get("determination_date_portal"):
        row["determination_date"] = nm["determination_date_portal"]
        row["date_source"] = "portal-node-metadata"
    elif ex.get("execution_year"):
        row["determination_date"] = ex["execution_year"]
        row["date_source"] = "instrument:year-only(" + ex.get("parse_note", "")[:40] + ")"
    m = re.search(r"\b(SSD-\s?\d+|MP\d+_\d+|SSD\s\d+)\b", flat)
    row["case_id"] = re.sub(r"\s+", "", m.group(1)) if m else ""
    m = re.search(r"Applicant\s*:?\s*([A-Z][A-Za-z0-9 ,\.\&\(\)\'\-]{4,110}?)(?=\s*(?:Consent Authority|Site\s*:|Development\s*:|ABN|ACN))", flat)
    row["applicant"] = re.sub(r"\s+", " ", m.group(1)).strip() if m else ""
    m = re.search(r"Consent Authority\s*:?\s*([A-Za-z ,\.]{4,70}?)(?=\s*(?:Site|Development|Applicant|:))", flat)
    auth = re.sub(r"\s+", " ", m.group(1)).strip() if m else ""
    if auth.split()[:1] and auth.split()[0].lower() in ("site", "development", "applicant"):
        auth = ""  # captured the next label, not a value (two-column layouts)
    if not auth or not row["applicant"]:
        # interleaved two-column Schedule 1 (dicker 2018): labels and values are separated;
        # values run "SSD <n> <Applicant> <Consent Authority> <Site> ..." after SCHEDULE 1
        m2 = re.search(r"SCHEDULE 1\s+SSD\s?-?\s?\d+\s+([A-Z][^:]{3,70}?)\s+"
                       r"(Minister for Planning(?: and Public Spaces)?|Minister for Planning,? Industry"
                       r" and Environment|NSW Independent Planning Commission|[^\s]{3,60} Council)\b", flat)
        if m2:
            row["applicant"] = row["applicant"] or m2.group(1).strip()
            auth = auth or m2.group(2)
    m3 = re.search(r"(Minister for Planning(?: and Public Spaces| and Homes|, Industry and Environment)?"
                   r"|NSW Independent Planning Commission|[\w'\-]{3,40} Council)", auth or "")
    row["consent_authority"] = m3.group(1) if m3 else auth
    for key, pat in BATTERY.items():
        row[key] = first(pat, flat)
    # counts for the presence-only tests
    for key, pat in BATTERY.items():
        if row[key] == "yes":
            row[key] = str(len(re.findall(pat, flat, re.I)))
    # manual reliability review (documented in MANUAL_RELIABLE)
    slug_u = re.sub(r"[^A-Za-z0-9]+", "_", slug)[:70]
    if not row["reliable"] and slug_u in MANUAL_RELIABLE:
        row["reliable"] = True
        row["reliable_note"] = "manual-review: " + MANUAL_RELIABLE[slug_u]
    else:
        row["reliable_note"] = ""
    return row


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--list", action="store_true")
    p.add_argument("--limit", type=int, default=None)
    p.add_argument("--pack", action="store_true", help="also emit a loadable curated pack")
    p.add_argument("--only", action="append", default=[], help="restrict to these project slugs")
    p.add_argument("--offline", action="store_true",
                   help="re-analyse the archived PDFs/texts: no network, no re-extraction")
    a = p.parse_args(argv)

    slugs = sorted(os.path.basename(f)[:-5] for f in glob.glob(os.path.join(NODES, "*.json")))
    # only determined/approved originals, not modifications
    det = []
    for s in slugs:
        node = json.load(open(os.path.join(NODES, f"{s}.json"), encoding="utf-8"))
        stage = ((node.get("field_case_stage") or [{}])[0].get("value") or "")
        decision = ((node.get("field_decision") or [{}])[0].get("value") or "")
        if stage == "Determination" and decision.lower().startswith("approv"):
            picked = pick_consent(s)
            if picked:
                det.append((s, picked[0]))
    if a.only:
        det = [d for d in det if d[0] in a.only]
    print(f"{len(det)} determined projects have an identifiable consent document")

    if a.list:
        for s, att in det:
            print(f"  {s[:52]:54s} {att[:64]}")
        return 0

    limit = a.limit if a.limit is not None else (len(det) if a.offline else 10)
    os.makedirs(ATT, exist_ok=True)
    os.makedirs(os.path.dirname(OUT_CSV), exist_ok=True)
    rows, skipped = [], []

    if a.offline:
        for i, (slug, att) in enumerate(det[:limit], 1):
            name = re.sub(r"[^A-Za-z0-9]+", "_", slug)[:70]
            pdf = os.path.join(ATT, name + ".pdf")
            txt_p = os.path.join(ATT, name + ".txt")
            meta_p = pdf + ".meta.json"
            print(f"[{i}/{min(limit, len(det))}] {slug} (offline)")
            if not (os.path.exists(pdf) and os.path.exists(txt_p) and os.path.getsize(txt_p) > 0):
                print("    no cached extraction - run scripts/reextract_consents.py first")
                skipped.append((slug, "no cached extraction")); continue
            nmeta = json.load(open(meta_p)) if os.path.exists(meta_p) else {}
            digest = hashlib.sha256(open(pdf, "rb").read()).hexdigest()
            if nmeta.get("sha256") and nmeta["sha256"] != digest:
                print("    SHA-256 MISMATCH against fetch manifest - refusing to analyse")
                skipped.append((slug, "sha mismatch")); continue
            meta = dict(nmeta.get("extraction") or {})
            meta["title"] = nmeta.get("title") or ""
            with open(txt_p, encoding="utf-8", errors="replace") as fh:
                txt = fh.read()
            row = analyse(slug, txt, meta)
            rows.append(row)
            flag = "" if row["reliable"] else "  <-- LOW YIELD, negatives unsafe"
            print(f"    {row['chars']:>9,} chars  det={row['determination_date'] or '?':10s}"
                  f" ({row['date_source'][:26]})  by={row['signatory_name'][:24] or '?'}{flag}")
    else:
        for i, (slug, att) in enumerate(det[:limit], 1):
            print(f"[{i}/{min(limit, len(det))}] {slug}")
            try:
                info = resolve(att)
            except urllib.error.HTTPError as exc:
                print(f"    resolve {exc.code} - restricted"); skipped.append((slug, f"resolve HTTP {exc.code}"))
                time.sleep(DELAY); continue
            except Exception as exc:  # noqa: BLE001
                print(f"    resolve failed {exc}"); skipped.append((slug, str(exc)))
                time.sleep(DELAY); continue
            if info["is_public"] is False:
                print("    field_is_public=false - skipping"); skipped.append((slug, "not public")); continue
            if not info["uri"]:
                skipped.append((slug, "no uri")); continue
            try:
                body = get(info["uri"])
            except Exception as exc:  # noqa: BLE001
                print(f"    download failed {exc}"); skipped.append((slug, str(exc)))
                time.sleep(DELAY); continue
            if len(body) > MAX_BYTES:
                print(f"    {len(body):,} bytes exceeds the {MAX_BYTES:,} cap - skipping")
                skipped.append((slug, "too large")); time.sleep(DELAY); continue
            name = re.sub(r"[^A-Za-z0-9]+", "_", slug)[:70]
            path = os.path.join(ATT, name + ".pdf" if body[:5] == b"%PDF-" else name + ".bin")
            open(path, "wb").write(body)
            with warnings.catch_warnings(record=True) as caught:
                warnings.simplefilter("always")
                txt = extract(path, warn=False)
            st = yield_stats(path, len(txt))
            json.dump({"url": info["uri"], "attachment_slug": att, "title": info["title"],
                       "folder": info["folder"], "label": info["label"], "is_public": info["is_public"],
                       "fetched_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                       "sha256": hashlib.sha256(body).hexdigest(), "bytes": len(body),
                       "extraction": st}, open(path + ".meta.json", "w"), indent=1)
            open(path.replace(".pdf", ".txt").replace(".bin", ".txt"), "w", encoding="utf-8").write(txt)
            row = analyse(slug, txt, st)
            rows.append(row)
            flag = "" if st["reliable"] else "  <-- LOW YIELD, negatives unsafe"
            print(f"    {len(body):>9,} B  {st['chars']:>7,} chars  {st['chars_per_kb']:>6.1f} c/KB"
                  f"  applicant={row['applicant'][:44] or '?'}{flag}")
            time.sleep(DELAY)

    if not rows:
        print("nothing analysed", file=sys.stderr)
        return 1
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    print(f"\nwrote {OUT_CSV} ({len(rows)} consents, {len(skipped)} skipped)")

    reliable = [r for r in rows if r["reliable"]]
    print(f"\n=== condition battery across {len(reliable)} reliably-extracted consents ===")
    keys = [k for k in BATTERY]
    print(f"{'condition':32s}{'n present':>10s}   projects")
    for k in keys:
        hits = [r["project"] for r in reliable if r.get(k)]
        print(f"{k:32s}{len(hits):>10d}   {', '.join(h[:26] for h in hits[:5])}")
    print(f"\n=== applicants ===")
    for r in reliable:
        print(f"  {r['project'][:44]:46s} {r['case_id']:16s} {r['applicant'][:60] or '(not parsed)'}")

    if a.pack:
        lowyield = [r["project"] for r in rows if not r["reliable"]]
        pack = {
            "pack_id": "rg060-consent-conditions",
            "prepared_by": "scripts/consent_condition_audit.py",
            "prepared_on": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            "sources": [dict(
                id=SRC,
                title="Signed development consents for determined NSW data centre State Significant "
                      "Developments (bulk harvest)",
                publisher="NSW Department of Planning, Housing and Infrastructure",
                url="https://www.planningportal.nsw.gov.au/major-projects/search?"
                    "field_case_type_value=State+Significant+Development&combine=Data+Centre",
                doc_type="primary_planning_portal", published=None, credibility="A",
                accessed=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                notes=f"{len(rows)} consent documents downloaded from the portal's public attachment "
                      f"endpoints and archived under data/raw/nsw_planning/consents/ with SHA-256 manifests and "
                      f"per-document extraction yield statistics. {len(reliable)} extracted above the "
                      f"{20} chars/KB reliability floor and support negative findings; "
                      f"{len(lowyield)} fell below it and are recorded as extraction-limited, NOT as evidence "
                      f"of absence: {', '.join(lowyield) or 'none'}. {len(skipped)} projects were skipped "
                      f"(restricted, oversized or unresolvable). Condition battery and Schedule 1 applicant "
                      f"parsed per document; matrix at exports/nsw_planning/nsw_dc_consent_conditions.csv.")],
            "rows": {
                "metrics": [
                    dict(as_of=datetime.now(timezone.utc).strftime("%Y-%m"), scope="NSW",
                         metric_name="consents_analysed_reliably", value=float(len(reliable)), unit="count",
                         basis="actual",
                         notes="Signed consents extracted above the reliability floor, so their negative "
                               "findings are safe to rely on.",
                         fact_status="VERIFIED", confidence="high",
                         as_of_date=datetime.now(timezone.utc).strftime("%Y-%m-%d"), source_id=SRC),
                    dict(as_of=datetime.now(timezone.utc).strftime("%Y-%m"), scope="NSW",
                         metric_name="consents_extraction_limited", value=float(len(lowyield)), unit="count",
                         basis="actual",
                         notes="Consents whose text extraction fell below the reliability floor. Recorded so "
                               "that nobody treats a keyword miss in them as evidence of absence.",
                         fact_status="VERIFIED", confidence="high",
                         as_of_date=datetime.now(timezone.utc).strftime("%Y-%m-%d"), source_id=SRC),
                ],
                "research_gaps": [],
            },
        }
        # per-consent metrics for the headline conditions
        for k in ("renewable_ppa_additionality", "pue", "nox_mass_cap", "generator_hours_cap",
                  "website_disclosure", "guidelines_cited"):
            n = sum(1 for r in reliable if r.get(k))
            pack["rows"]["metrics"].append(dict(
                as_of=datetime.now(timezone.utc).strftime("%Y-%m"), scope="NSW",
                metric_name=f"consents_with_{k}", value=float(n), unit="count", basis="actual",
                notes=f"Of {len(reliable)} reliably-extracted signed consents for determined NSW data centre "
                      f"SSDs, {n} contain a {k.replace('_', ' ')} provision.",
                fact_status="VERIFIED", confidence="high",
                as_of_date=datetime.now(timezone.utc).strftime("%Y-%m-%d"), source_id=SRC))
        os.makedirs(os.path.dirname(OUT_PACK), exist_ok=True)
        with open(OUT_PACK, "w", encoding="utf-8") as fh:
            json.dump(pack, fh, indent=1)
        print(f"\nwrote {OUT_PACK}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
