#!/usr/bin/env python3
"""
Regenerate the post-load documentation artifacts from the FINAL database.

Why this exists
---------------
scripts/build_db.py writes reports/build_report.md and viewer/db.json while it builds - i.e.
BEFORE any curated pack loads. Both artifacts were therefore seed-stage snapshots: the viewer
JSON showed 41 metrics and zero case_handling rows against a database holding 325 and 83, and
the build report claimed 326 rows and 60 sources against ~1,500 rows and 117 sources. Defect #4
found on 2026-09-18 (after #1 stale CSVs, #2 duplicate rows on pack re-run, #3 the orphaned
rg060 pack).

This script runs LAST in both drivers (rebuild_all.py and `make docs`), after load_pack and
export_csv, and rewrites both artifacts from the database as loaded:
  * viewer/db.json          - every table and view, same shape build_db.py used
  * reports/build_report.md - final counts, verification ledger, unverified material, pipeline
                              by state, and the FULL research-gap register from the database
                              (build_db.py only ever listed the seed gaps).

Run: python3 scripts/finalize_docs.py
"""
from __future__ import annotations

import json
import os
import sqlite3
import sys
from datetime import date, datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = os.path.join(ROOT, "exports", "australian_data_centre_observatory.db")
REPORT = os.path.join(ROOT, "reports", "build_report.md")
VIEWER = os.path.join(ROOT, "viewer", "db.json")


def main() -> int:
    conn = sqlite3.connect(DB)
    tables = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")]
    views = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='view' ORDER BY name")]

    counts = {t: conn.execute(f'SELECT COUNT(*) FROM "{t}"').fetchone()[0] for t in tables}
    total = sum(counts.values())
    refs = counts.get("source_refs", 0)
    data_rows = total - refs

    # ---- viewer dump ---------------------------------------------------------
    dump = {}
    for t in tables + views:
        cur = conn.execute(f'SELECT * FROM "{t}"')
        cols = [d[0] for d in cur.description]
        dump[t] = [dict(zip(cols, r)) for r in cur.fetchall()]
    os.makedirs(os.path.dirname(VIEWER), exist_ok=True)
    with open(VIEWER, "w", encoding="utf-8") as fh:
        json.dump(dump, fh, indent=1, default=str)

    # ---- integrity spot checks (the report must not claim what it has not checked) ----
    problems = []
    dangling = conn.execute(
        "SELECT COUNT(*) FROM source_refs sr LEFT JOIN sources s ON s.id=sr.source_id "
        "WHERE s.id IS NULL").fetchone()[0]
    if dangling:
        problems.append(f"{dangling} source_refs point at sources that do not exist")
    for tbl in ("metrics", "case_handling"):
        n = conn.execute(f"SELECT COUNT(*) FROM {tbl} WHERE source_id IS NULL OR source_id=''"
                         ).fetchone()[0]
        if n:
            problems.append(f"{tbl}: {n} rows without source_id")
    # Informational: research gaps are questions, not claims; the seed-stage methodology gaps
    # legitimately carry no source. Counted, reported, but not a failure.
    gaps_nosrc = conn.execute(
        "SELECT COUNT(*) FROM research_gaps WHERE source_id IS NULL OR source_id=''").fetchone()[0]

    # ---- build report ---------------------------------------------------------
    n_res = conn.execute(
        "SELECT COUNT(*) FROM research_gaps WHERE status='resolved'").fetchone()[0]
    lines = [
        "# ADCO build report",
        "",
        f"Generated: {date.today().isoformat()} (FINAL, post-load - regenerated by "
        f"scripts/finalize_docs.py at {datetime.now(timezone.utc).strftime('%H:%M UTC')}; "
        f"the seed-stage report written by build_db.py is superseded)",
        "",
        "- Database: `exports/australian_data_centre_observatory.db`",
        f"- Tables: {len(tables)}  |  Views: {len(views)}  |  Data rows: {data_rows} "
        f"(+ {refs} source_refs = {total} total)",
        f"- Sources catalogued: {counts.get('sources', 0)}",
        f"- Integrity problems: {len(problems)}",
        "",
        "## Row counts",
        "",
        "| Table | Rows |",
        "|---|---|",
    ]
    for t in tables:
        lines.append(f"| {t} | {counts[t]} |")

    lines += ["", "## Verification ledger (fact_status x confidence)", "",
              "| Table | fact_status | confidence | rows |", "|---|---|---|---|"]
    for tbl, fs, cf, n in conn.execute(
            "SELECT * FROM v_verification_ledger ORDER BY tbl, fact_status"):
        lines.append(f"| {tbl} | {fs} | {cf} | {n} |")

    lines += ["", "## Unverified / claimed material that must not be published as fact", ""]
    for tbl, fs, n in conn.execute(
            "SELECT 'sites', fact_status, COUNT(*) FROM sites WHERE fact_status IN ('CLAIMED','GAP') GROUP BY 2 "
            "UNION ALL SELECT 'entities', fact_status, COUNT(*) FROM entities WHERE fact_status IN ('CLAIMED','GAP') GROUP BY 2 "
            "UNION ALL SELECT 'incentives', fact_status, COUNT(*) FROM incentives WHERE fact_status IN ('CLAIMED','GAP') GROUP BY 2 "
            "UNION ALL SELECT 'renewable_claims', fact_status, COUNT(*) FROM renewable_claims GROUP BY 2 "
            "UNION ALL SELECT 'metrics', fact_status, COUNT(*) FROM metrics WHERE confidence='low' GROUP BY 2"):
        lines.append(f"- {tbl}: {fs} = {n}")

    lines += ["", "## Pipeline by state (v_pipeline_by_state)", "",
              "| State | Market | Status | Sites | MW | Capex A$bn |", "|---|---|---|---|---|---|"]
    for r in conn.execute("SELECT * FROM v_pipeline_by_state"):
        lines.append("| " + " | ".join(str(x) for x in r) + " |")

    lines += ["", "## Problems", ""]
    lines += [f"- {p}" for p in problems] if problems else ["None."]
    if gaps_nosrc:
        lines.append(f"- note: {gaps_nosrc} research gaps carry no source_id (seed-stage "
                     "methodology questions - gaps are questions, not claims; informational only)")

    lines += ["", f"## Research-gap register ({n_res} resolved)", "",
              "| ID | Pillar | Pri | Status | Method | Question |", "|---|---|---|---|---|---|"]
    for gid, pillar, prio, status, method, q in conn.execute(
            "SELECT id,pillar,priority,status,retrieval_method,question FROM research_gaps "
            "ORDER BY CASE status WHEN 'open' THEN 0 WHEN 'in_progress' THEN 1 WHEN 'blocked' THEN 2 "
            "ELSE 3 END, priority, id"):
        lines.append(f"| RG-{gid:03d} | {pillar} | {prio} | {status} | {method} | {q[:150]} |")

    with open(REPORT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    conn.close()
    print(f"wrote {REPORT} and {VIEWER}")
    print(f"final: {data_rows} data rows + {refs} source_refs across {len(tables)} tables, "
          f"{len(views)} views; problems: {len(problems)}")
    for p in problems:
        print("  !", p)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
