/**
 * An export back into SQL.
 *
 * The restore follows the same discipline as the pipeline loader: it emits a
 * transactional artefact for a human to read, and writes to no database
 * itself. Recovering from a backup is exactly the moment when an unreviewed
 * write is most dangerous and least likely to be questioned.
 *
 * Value rendering is deliberately not shared with lib/ingestion/sql.ts. That
 * module emits a known fixed shape and treats every object as jsonb, which is
 * correct there and wrong here: editorial.essays carries text[] and uuid[]
 * columns, and a backup has to round-trip whatever the column actually was.
 */

import { BACKUP_TABLES, type BackupTable } from '@/lib/backup/tables';
import type { Manifest } from '@/lib/backup/manifest';

export const RESTORE_VERSION = 'restore-backup/1.0.0';

/**
 * A Postgres array literal, as a quoted string.
 *
 * Rendered as '{a,b}' rather than ARRAY[a,b] because the quoted form coerces
 * to any array type in assignment context — text[] and uuid[] alike — and
 * because the empty array needs no explicit cast this way. ARRAY[] would raise
 * "cannot determine type of empty array".
 */
export function arrayLiteral(values: readonly unknown[]): string {
  const elements = values.map((value) => {
    if (value === null || value === undefined) return 'NULL';
    const text = typeof value === 'object' ? JSON.stringify(value) : String(value);
    // Quote anything that could be misread as structure, and NULL itself so a
    // literal string "NULL" does not come back as a null element.
    if (text === '' || /[{},"\\\s]/.test(text) || text.toUpperCase() === 'NULL') {
      return `"${text.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
    }
    return text;
  });
  return `'{${elements.join(',')}}'`;
}

/** A SQL literal for one exported value. */
export function literal(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) {
      throw new Error(`Refusing to emit a non-finite number: ${value}`);
    }
    return String(value);
  }
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (Array.isArray(value)) return arrayLiteral(value);
  if (typeof value === 'object') {
    return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

/**
 * Insert statements for one table's rows.
 *
 * Batched so a table of a few thousand rows does not become one statement
 * megabytes wide, which is awkward to review and awkward for a server to
 * report an error position in.
 */
export function insertsFor(
  table: BackupTable,
  rows: readonly Record<string, unknown>[],
  batchSize = 200,
): string {
  if (rows.length === 0) return `-- ${table.name}: no rows\n`;

  const columns = Object.keys(rows[0] as Record<string, unknown>).sort();
  for (const [index, row] of rows.entries()) {
    const keys = Object.keys(row).sort();
    if (keys.length !== columns.length || keys.some((k, i) => k !== columns[i])) {
      throw new Error(
        `Row ${index} of ${table.name} has different columns to row 0. ` +
          'The export is inconsistent and must not be restored.',
      );
    }
  }

  const key = new Set(table.primaryKey);
  const updates = columns.filter((c) => !key.has(c));
  if (updates.length === 0) {
    throw new Error(`${table.name} has no non-key columns to update on conflict.`);
  }

  const chunks: string[] = [];
  for (let start = 0; start < rows.length; start += batchSize) {
    const batch = rows.slice(start, start + batchSize);
    const values = batch
      .map((row) => '  (' + columns.map((c) => literal(row[c])).join(', ') + ')')
      .join(',\n');
    chunks.push(
      `insert into ${table.name} (${columns.join(', ')})\nvalues\n${values}\n` +
        `on conflict (${table.primaryKey.join(', ')}) do update set\n` +
        updates.map((c) => `  ${c} = excluded.${c}`).join(',\n') +
        ';\n',
    );
  }
  return chunks.join('\n');
}

/**
 * The whole restore artefact.
 *
 * One transaction, foreign key order, and a row count assertion per table that
 * rolls the restore back if what landed does not match what the manifest
 * promised.
 */
export function buildRestoreSql(input: {
  manifest: Manifest;
  rowsByTable: ReadonlyMap<string, readonly Record<string, unknown>[]>;
  /** Restore only the tables that cannot be rebuilt from data-pipeline/. */
  curatedOnly?: boolean;
}): string {
  const { manifest, rowsByTable, curatedOnly = false } = input;

  const tables = BACKUP_TABLES.filter((t) => {
    if (curatedOnly && t.recoverability !== 'curated') return false;
    return rowsByTable.has(t.name);
  });

  const parts: string[] = [
    `-- Generated by ${RESTORE_VERSION}. Do not edit by hand.`,
    '--',
    `-- Restores the backup taken at ${manifest.takenAt} from ${manifest.sourceHost}.`,
    curatedOnly
      ? '-- Curated tables only: everything else is rebuilt with npm run load:pipeline.'
      : '-- Every backed up table.',
    '--',
    '-- This UPSERTS. It does not delete. A row created after the backup was',
    '-- taken survives the restore, so this recovers lost or corrupted rows but',
    '-- does not rewind the database to the backup as a whole. If that is what',
    '-- you need, restore into an empty database instead.',
    '--',
    '-- Read it before applying it. Recovering from a backup is exactly when an',
    '-- unreviewed write is most dangerous.',
    '',
    'begin;',
    '',
  ];

  for (const table of tables) {
    const rows = rowsByTable.get(table.name) ?? [];
    parts.push(`-- ${table.name} (${table.recoverability}): ${table.note}`);
    parts.push(insertsFor(table, rows));
  }

  parts.push('-- Row counts, checked inside the transaction.');
  parts.push('do $$');
  parts.push('declare');
  parts.push('  found integer;');
  parts.push('begin');
  for (const table of tables) {
    const expected = manifest.tables.find((t) => t.name === table.name)?.rows ?? 0;
    parts.push(`  select count(*) into found from ${table.name};`);
    parts.push(`  if found < ${expected} then`);
    parts.push(
      `    raise exception 'ROLLED BACK: ${table.name} holds % rows, the backup had ${expected}', found;`,
    );
    parts.push('  end if;');
  }
  parts.push('end;');
  parts.push('$$;');
  parts.push('');
  parts.push('commit;');
  parts.push('');

  return parts.join('\n');
}
